### ISSUE TITLE
Uncaught TypeError: this.show is not a function

### ISSUE THREAD

**Issue by manogna4** [lejsue/symbols-navigator#4]
[Enter steps to reproduce:]

1. <symbols navigator: toggle focus> does not work from command palette

**Atom**: 1.21.1 x64
**Electron**: 1.6.15
**OS**: Microsoft Windows 10 Home
**Thrown From**: [symbols-navigator](https://github.com/lejsue/symbols-navigator) package 1.0.1

### Stack Trace

Uncaught TypeError: this.show is not a function

```
At C:\Users\manogna\.atom\packages\symbols-navigator\lib\symbols-navigator-view.js:143

TypeError: this.show is not a function
    at SymbolsNavigatorView.toggleFocus (/packages/symbols-navigator/lib/symbols-navigator-view.js:143:12)
    at HTMLElement.symbolsNavigatorToggleFocus (/packages/symbols-navigator/lib/symbols-navigator.js:81:75)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.21.1/resources/app/src/command-registry.js:381:36)
    at Object.didConfirmSelection (~/AppData/Local/atom/app-1.21.1/resources/app/node_modules/command-palette/lib/command-palette-view.js:144:35)
    at SelectListView.confirmSelection (~/AppData/Local/atom/app-1.21.1/resources/app/node_modules/command-palette/node_modules/atom-select-list/src/select-list-view.js:327:26)
    at HTMLDivElement.core:confirm (~/AppData/Local/atom/app-1.21.1/resources/app/node_modules/command-palette/node_modules/atom-select-list/src/select-list-view.js:84:20)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.21.1/resources/app/src/command-registry.js:381:36)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (~/AppData/Local/atom/app-1.21.1/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.21.1/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.21.1/resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (~/AppData/Local/atom/app-1.21.1/resources/app/src/window-event-handler.js:3:65)
```

### Commands

```
  3x -2:55.9.0 core:move-up (div.symbols-navigator.tool-panel.focusable-panel)
  4x -2:38.1.0 core:move-down (div.symbols-navigator.tool-panel.focusable-panel)
  3x -2:10.1.0 core:move-up (div.symbols-navigator.tool-panel.focusable-panel)
  8x -2:09.1.0 core:move-down (div.symbols-navigator.tool-panel.focusable-panel)
     -0:38.1.0 command-palette:toggle (div.package-readme.native-key-bindings)
     -0:35.5.0 core:move-down (input.hidden-input)
     -0:35.1.0 core:confirm (input.hidden-input)
     -0:35.1.0 symbols-navigator:toggle-focus (div.package-readme.native-key-bindings)
 63x -0:25.9.0 core:move-up (input.hidden-input)
 33x -0:21 core:move-down (input.hidden-input)
 23x -0:18.1.0 intentions:highlight (input.hidden-input)
     -0:16.9.0 command-palette:toggle (input.hidden-input)
  3x -0:13.3.0 editor:delete-to-beginning-of-word (input.hidden-input)
     -0:10 core:move-down (input.hidden-input)
     -0:09.6.0 core:confirm (input.hidden-input)
     -0:09.6.0 symbols-navigator:toggle-focus (input.hidden-input)
```

### Non-Core Packages

```
atom-ide-ui 0.5.1 
atom-jinja2 0.6.0 
autoclose-html 0.23.0 
autocomplete-python 1.10.3 
busy-signal 1.4.3 
file-icons 2.1.13 
goto-definition 1.3.4 
ide-json 0.1.0 
intentions 1.1.5 
linter 2.2.0 
linter-pylama 0.9.4 
linter-ui-default 1.6.10 
symbols-navigator 1.0.1 
tree-view-sort 0.8.1 
```

**Comment by lejsue** [comment]
Thanks for the report, and sorry for my late reply.
I'll figure out and try to fix it as soon as possible.

**Comment by lejsue** [comment]
Hi,
I found that there is a missing function, I already fixed it. But I typed wrong issue number in commit. I put it in issue 3. lol

Just let me know if there is still problem. Thx!

**Comment by manogna4** [comment]
the package doesn't crash anymore, but 'symbols navigator: toggle focus' still does not do much apart from toggling the navigator panel. For example, I am not able to move to different symbols using the cursor keys on the keyboard

**Comment by lejsue** [comment]
Hi,
Do you mean as the function of using keyboard to open file in tree-view? (using alt+\ and then moving cursor by keyboard)
This function is really interesting, let me figure out how to implement in symbols-navigator. :-)

**Comment by manogna4** [comment]
That would be great :-)
I think firing 'symbols navigator: toggle focus' moves focus to it already.
It's just that one needs to use the mouse to scroll and double click
navigate to a symbol after that.
The ability to use up/down to move around, left/right to conrtact/expand
groups, and enter to move to that symbol would be great.

**Comment by lejsue** [comment]
Hi,
I coded some keyboard events of up/down/left/right/enter in v1.2.0.
I not usually use command palette, but I tested it before release, it is ok. Please see if it is ok for you too.
If you find some bugs, please let me know!
Thanks a lot.

**Comment by manogna4** [comment]
this works great! :-) I use it extensively.

I haven't found any bugs so far, but I do have a suggestion:
the up/down events allow you to move one symbol at a time. A page up/ page
down event could be used to navigate one screen at a time. This is very
useful while navigating long files.

Thanks for all your work

**Comment by lejsue** [comment]
Sure, it's not too complicated. I have committed code, and will push to atom later.
